[[redirects]]
  from = "/p/*"
  to = ":splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "https://msbell.harker.xyz"}
[[redirects]]
  from = "/pgtm/*"
  to = "https://www.googletagmanager.com/gtm.js:splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "https://msbell.harker.xyz"}
[[redirects]]
  from = "/docs/*"
  to = "https://harker-ms-bell-docs.netlify.com/:splat"
  status = 200
[[redirects]]
  from = "/admin/*"
  to = "https://harker-ms-bell-admin.netlify.com/:splat"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://msbell-backend.harker.xyz/api/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200